name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cocoapods
      run: gem install cocoapods
    - name: Install pods
      run: pod install
    - name: Build and run tests
      run: xcodebuild -workspace Gagaebu.xcworkspace -scheme GagaebuTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.4.1' test
